### ISSUE TITLE
Plugin seems to lose contact - HomeBridge restart solves

### ISSUE THREAD

**Issue by ultrathew** [MortJC/homebridge-platform-orbit#10]
First off - thank you for creating this. It's hopefully going to help me to automate something that I had given up on. Basically I don't need to control my B•Hyve faucet timers, I just need to be able to read their status so I can shut off my house's water treatment system when I am running my watering programs.

I have been able to get everything to work as expected - via a manual water or a scheduled one - which is great. The problem is the plugin seems to stop correctly reporting the status of the faucets at some point and can't get it back. I can always get it to work again if I restart HomeBridge, but it eventually will break again. Happy to share any logs. Thanks!

**Comment by MortJC** [comment]
Hi.

Happy to assist. Can you run homebridge in debug mode and send me the logs
once it fails.

Cheers.

**Comment by frensley** [comment]
Hey there,
I've noticed this issue as well. I had a power outage last night and noticed this behavior as the reestablishment of Internet connectivity was slower than Homebridge initialization.  Looking at the logs it appears that it only tries twice to initialize itself. Restarting Homebridge, of course, resolved this issue. The SmartThings plugin continued to try and was eventually successful. I'm not sure if it is this particular problem, but it could be a contributor.

Logs:
```[5/24/2020, 8:18:20 PM] [orbit] Initializing orbit platform...
[5/24/2020, 8:18:20 PM] [orbit] Starting OrbitPlatform using homebridge API 2.6
[5/24/2020, 8:18:20 PM] [orbit] Remembered accessory, configuring handlers Smart Hose Timer 1
[5/24/2020, 8:18:20 PM] [orbit] Fetch the devices
[5/24/2020, 8:18:22 PM] [Config] Homebridge Config UI X v4.20.0 is listening on :: port 8080
[5/24/2020, 8:18:20 PM] Homebridge is running on port 53757.
[5/24/2020, 8:18:25 PM] [orbit] Error: getaddrinfo EAI_AGAIN api.orbitbhyve.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.orbitbhyve.com'
}
[SmartThings-v2] ERROR: getDevices Error | Possible Internet/Network/DNS Error | Unable to reach the uri | Message getaddrinfo EAI_AGAIN graph-na02-useast1.api.smartthings.com
[SmartThings-v2] ALERT: Total Initialization Time: (5 seconds)
[SmartThings-v2] NOTICE: Unknown Capabilities: []
[SmartThings-v2] INFO: SmartThings DeviceCache Size: (7)
[SmartThings-v2] INFO: WebServer Initiated...
[SmartThings-v2] INFO: Sending StartDirect Request to SmartThings | SendToLocalHub: (false)
[SmartThings-v2] INFO: Direct Connect Active | Listening at 172.17.0.1:8000
[SmartThings-v2] INFO: INFO: Your plugin version is up-to-date
[SmartThings-v2] NOTICE: Sending Plugin Status to SmartThings | UpdateAvailable: false
[5/24/2020, 8:18:30 PM] [orbit] Error: getaddrinfo EAI_AGAIN api.orbitbhyve.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.orbitbhyve.com'
}
(node:379) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at PlatformOrbit.<anonymous> (/homebridge/node_modules/homebridge-platform-orbit/platform.js:51:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:379) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[SmartThings-v2] ERROR: sendStartDirect Error | Possible Internet/Network/DNS Error | Unable to reach the uri | Message getaddrinfo EAI_AGAIN graph-na02-useast1.api.smartthings.com
[SmartThings-v2] ERROR: sendUpdateStatus Error | Possible Internet/Network/DNS Error | Unable to reach the uri | Message getaddrinfo EAI_AGAIN graph-na02-useast1.api.smartthings.com```

**Comment by MortJC** [comment]
Hi,

It looks like homebridge was restarted and your network was not yet up. The
Orbit plugins first step of logging in to get a list of your devices
failed. And it only does this at start up.

SmartThings recovered as it refreshes the device list every hour.

I'll improve the error handling, but I don't think it's necessary to handle
this edge case.

Cheers.

**Comment by frensley** [comment]
@MortJC Thanks for looking into this. I surmised the network issue as well. I think the main reason I pointed this out, is that the Orbit plugin didn't recover from that while others did; leading to a potentially confusing outcome.  I agree, probably an edge case.
