### ISSUE TITLE
Irrigation Timer Resets to Start On Refresh

### ISSUE THREAD

**Issue by Mongorlio** [MortJC/homebridge-platform-orbit#11]
I am using this plugin with homebridge to control my Orbit Bhyve irrigation timer. I have three zones setup. If I use homekit to turn on a zone, the timer starts as expected per my settings (15 minute timer) within the accessory in homekit. What is unexpected is that if I leave the page and come back, the timer starts counting down again from the original setting of 15 minutes. The actual running of the accessory timer seems to work properly, but the visual display of the time remaining doesn't properly reflect the time that has elapsed.

**Comment by MortJC** [comment]
Hi. Thanks for the feedback. I've updated the calculation for the remaining
duration and released version 1.4.0.
