### ISSUE TITLE
Change Logs in Config-UI-X

### ISSUE THREAD

**Issue by mitch7391** [MortJC/homebridge-platform-orbit#12]
Hey @MortJC I was wondering if you can make your change logs appear in config-ui-x? Some plugins when updated on that UI have a pop-up box that lists the latest updates to the plug-in :) I believe all you need to do is move the Changelog from README.md to the CHANGELOG.md file. I am quoting the developer of the homebridge-xiaomi-roborock-vacuum for what he said he did when I raised the issue there.

**Comment by MortJC** [comment]
Sure. I've added it to the code base and will update it going forward.

**Comment by mitch7391** [comment]
Fairly certain I saw this one working g last update @MortJC :) should be good to close out? Thanks for your work!
