### ISSUE TITLE
B-Hyve is put into OFF mode (e.g. winterized) which stops Auto Watering programs 

### ISSUE THREAD

**Issue by maverixx** [MortJC/homebridge-platform-orbit#13]
Once a HomeKit activated watering session has completed, the B-Hyve is set to “off” mode rather than “Auto” mode. This means that B-Hyve stops its  programmed or smart watering activities. The “orbit off” mode is typically used for protection against frost during winter. It would therefore be better if the stop command could execute “auto” mode and not “off”.

On my b-have I have to reset the unit in order to override the “off” mode since the toggle is deactivated when using the Orbit app (e.g. settings in the app: //My B-Hyve/Devices/Device Run Mode/ ) in parallel with Homebridge.

**Comment by MortJC** [comment]
Hi,

Seems ok on mine. Which model of the B-Hyve do you havE?

Cheers.

**Comment by genesispc** [comment]
Also just wanted to let you know I am also seeing this issue. And again will get you some logs :-)
