### ISSUE TITLE
Zones not showing up

### ISSUE THREAD

**Issue by ultimatewooze** [MortJC/homebridge-platform-orbit#14]
Hi,
I have an issue with zones not showing up. I originally configured my Orbit with 2 zones. These did not show up and I tried everything with no success (restarting Homebridge, add manual zone programs in Orbit app etc). When I had given up these Eventually appeared in Homebridge. Now I have added two more zones and it is the same issue. Working in Orbit app but do not show up in Homebridge. 

Any pointers on what do do?
![E109B47B-4A33-421B-BA01-6EC8B10AC6E8](https://user-images.githubusercontent.com/67071178/85398643-d47c8780-b555-11ea-8769-13f5d9685b82.png)
![954D9B2D-AF01-4273-94B9-68B9A545AC92](https://user-images.githubusercontent.com/67071178/85398653-d8a8a500-b555-11ea-92ff-b615ccdbb374.jpeg)

**Comment by MortJC** [comment]
Hi,

Can you run it in debug mode and send me the output?
Also which model of the orbit do you have?

Cheers James.

**Comment by ultimatewooze** [comment]
Hi James,
The Orbit model is "Smart Outdoor Timer, 6 zones". Will send the log in PM.

/Peter

**Comment by ultimatewooze** [comment]
Hi James,
The model is "Smart outdoor timer, 6 zones". I have attached the logs.

Thanks
/Peter


[Homebridge log.txt](https://github.com/MortJC/homebridge-platform-orbit/files/4833297/Homebridge.log.txt)

**Comment by ultimatewooze** [comment]
Hi @MortJC 
As you can see from the attached screenshots the zones shows up in logs when I start them from the b-hyve app but is not added to Homebridge

![2000CAC5-778A-4A91-8DB8-9BB5DCF7621D](https://user-images.githubusercontent.com/67071178/86213979-d3adac00-bb7a-11ea-9200-76bcfbdf7482.jpeg)
![25C63B53-9F29-4B5E-81E3-18CCBEF0584B](https://user-images.githubusercontent.com/67071178/86213990-d7d9c980-bb7a-11ea-822a-6ba68dd2e324.jpeg)

**Comment by MortJC** [comment]
I really need the startup part of the log. Can you please send it to me, as
text rather than an image.

Cheers.

**Comment by ultimatewooze** [comment]
Hi @MortJC 
I have attached updated logs. Will send new tomorrow as program is scheduled for tonight which includes ""station":4".

Cheers,
[homebridge log 2.txt](https://github.com/MortJC/homebridge-platform-orbit/files/4860043/homebridge.log.2.txt)

**Comment by ultimatewooze** [comment]
Hi (again) @MortJC,
After renaming the zones in b-hyve app I noticed that this was not reflected in Homebridge. I tried to restart Homebridge several times but it kept the old naming. I therefore removed the plugin config, restarted Homebridge, added the config again. After a restart all zones showed up. I have attached updated logs which includes the above steps. 

Take care
/Peter
[Homebridge_log_3.txt](https://github.com/MortJC/homebridge-platform-orbit/files/4860099/Homebridge_log_3.txt)

**Comment by MortJC** [comment]
Hi,

Sorry, if the current issue is the naming, then this is a limitation of the
apple home implementation. The names can not be propagated from the bhyve
to the home application. You have to name them in the app.

Cheers.

**Comment by ultimatewooze** [comment]
Hi,
No. I removed the config info from Homebridge since I noticed that my updated names was not reflected in your plugin. Once added again all my zones appeared. 

So the solution to my problem was to remove the config input and re-add it again.
