### ISSUE TITLE
Siri not running all zones

### ISSUE THREAD

**Issue by TheBum** [MortJC/homebridge-platform-orbit#15]
I have a B-Hyve Indoor 4-zone timer. When I tell Siri “start the sprinklers”, she responds with “OK. Four valves are queued up for watering next.” However, only one zone runs, usually zone 4.

**Comment by MortJC** [comment]
Hi. The Bhyve can only run one sprinkler at a time. Homebridge will be
sending the commands to run each one at the same time. Likely the last one
is the one that will end up running. Hence Zone 4 will run.

**Comment by TheBum** [comment]
Is that something Homebridge could address?

**Comment by MortJC** [comment]
No. It's the bhyve that's only allowing you to run one zone at a time, and
it's doing this as most locations won't have the water pressure to run all
the sprinklers at the same time. Make sense?

**Comment by TheBum** [comment]
I wasn’t questioning sequencing zones. We’ve had this sprinkler system for almost 26 years, so I know most of the ins and outs. I’m only just now getting it networked.

Could the plug-in be modified to handle the sequencing, or does HomeBridge not provide enough info to it (e.g. the number of zones).

**Comment by MortJC** [comment]
The homebridge plugin does not replace the scheduling provide by the b-hyve itself. It only for running zone immediately and proving the status.

**Comment by TheBum** [comment]
So, basically, Siri is useless for B-Hyve timers with HomeBridge and this plugin unless you only have one zone?

**Comment by MortJC** [comment]
No, you can run each zone individually. E.g. Siri turn on the "Back garden"
sprinkler. Are you not able to do that?

**Comment by TheBum** [comment]
Once I renamed the zones in the Home app, it worked. It did not work with the default “Zone <n>” names.

**Comment by MortJC** [comment]
Great. Sorry I misunderstood your initial email.
