### ISSUE TITLE
Enhancement Request (config Duration)

### ISSUE THREAD

**Issue by jackc88** [MortJC/homebridge-platform-orbit#17]
Could you provide the ability to change duration values something we can set in the config or set larger hours, i.e., 2 hours, 3 hours, etc.  Thank You for the consideration.

**Comment by MortJC** [comment]
Hi, the duration options are controlled by the apple home. Sorry, not
something I can change.

**Comment by spiderguy84** [comment]
> Hi, the duration options are controlled by the apple home. Sorry, not something I can change.
> […](#)

I've seen setup videos for this plugin, and in it, his zones show at least up to 30 minutes, while mine gives two options of 5 or 10 minutes.

**Comment by MortJC** [comment]
Hmm.. I get from 5 min to 60 mins in 5 min intervals.

Are you running the latest iOS?

These intervals are set by the Apple Home app.

**Comment by codyc1515** [comment]
If you’re only seeing 5 & 10 minutes then I’m almost certain you are using iOS 14 beta as this is a known issue there. I recommend using the eve app in the interim.

**Comment by MortJC** [comment]
No update, closing.

**Comment by Aekung** [comment]
Not sure if this is still needed but you can increase the duration by using another application like "Eve Home" and set the duration from that application. The duration set in Eve Home will then carry-over to Home App and you will be able to select more duration on Home App.

**Comment by MortJC** [comment]
Thanks for the tip.
