### ISSUE TITLE
HomeKit Tile Doesn't Change Status

### ISSUE THREAD

**Issue by spiderguy84** [MortJC/homebridge-platform-orbit#19]
If I use Siri or Home app to start watering, it will say it is doing it, but the status will stay gray with just the word 'Scheduled' on it, as though it was not running.

**Comment by MortJC** [comment]
Hi, Can you run the home bridge in debug and send me the log?

**Comment by spiderguy84** [comment]
> Hi, Can you run the home bridge in debug and send me the log?
> […](#)

How do you run it in debug? I don’t see a debug option for the plug-in

**Comment by MortJC** [comment]
Take a look at
https://github.com/homebridge/homebridge/wiki/Basic-Troubleshooting.
Or if you are running Homebridge Config you can enable it there also.

**Comment by MortJC** [comment]
No update, closing.

**Comment by spiderguy84** [comment]
> Hi, Can you run the home bridge in debug and send me the log?
> […](#)

I finally got debug going. Any time the Homebridge UI window is open on a browser, it will update the home app and show that the system is running. If I close the browser window, it won't update the icon in the home app.
