### ISSUE TITLE
Same issue of Home app not updating when sprinkler running

### ISSUE THREAD

**Issue by spiderguy84** [MortJC/homebridge-platform-orbit#21]
Ok, so I didn't respond before the issue was closed, because I couldn't get it to mess up while the Homebridge window was running on Safari on my computer. If I was logged in to Homebridge UI on computer (home bridge running on Synology), the Home app would update to show that the water program was running, and the logs were normal. If the browser wasn't open and the Brydge app was doing watering, the home app on phone would never update to show that it was running. 

Since this is running on sinology, I shouldn't also have to be logged in on my computer to get it to work, should I?

**Comment by MortJC** [comment]
Hi,

That's very odd behaviour. Can you try running Home Bridge on a different
device as a test?

**Comment by spiderguy84** [comment]
> Hi, That's very odd behaviour. Can you try running Home Bridge on a different device as a test?
> […](#)

I tried this out using just HomeBridge on my MacBook and had the same issue...the home bridge page needs to be open on safari in order to reflect anything being active within the home app itself.

**Comment by MortJC** [comment]
Hi, can you please clarify what's not working?

With the homebridge website closed, if I start the watering on the home app
it shows me it's watering and the timer counts down. Is this not working
for you or something else?

**Comment by spiderguy84** [comment]
Pretty much. I can also start watering using home app and the icon won’t change, it will stay on waiting and then If I close out that view the platter for it just stays at scheduled even though it is running.

**Comment by MortJC** [comment]
Can you please confirm what iOS your are running, what HomeBridge version, what version of the Plugin and which Bhyve device you are using?

**Comment by spiderguy84** [comment]
iOS 14
Home Bridge Version 1.1.2
Plugin 1.4.3
BHyve Hose Faucet Timer

**Comment by MortJC** [comment]
Can you please update to the latest homebridge release 1.2.3.

**Comment by spiderguy84** [comment]
> Can you please update to the latest homebridge release 1.2.3. On Thu, Sep 24, 2020 at 5:39 AM spiderguy84 <notifications@github.com> wrote:
> […](#)

Ok, I updated, then closed the browser, started it up using b-hyve app, and the home app did update. I will test again later in the day without having the home bridge opened for at least a few hours, and see if it is still going ok.

**Comment by spiderguy84** [comment]
It worked yesterday, now back to the same issue. I have a screen recording of it, I’ll try to upload in a bit

**Comment by spiderguy84** [comment]
> Can you please update to the latest homebridge release 1.2.3. On Thu, Sep 24, 2020 at 5:39 AM spiderguy84 <notifications@github.com> wrote:
> […](#)

It worked yesterday, now is back to same deal. This time I did a screen recording showing how I even had HomeBridge opened in Safari, that it was indeed watering, and then showing what it says in Home app.  [http://www.316apps.com/bug/HomeBridge.mp4](url)
