### ISSUE TITLE
Unable to add to automations

### ISSUE THREAD

**Issue by fergymcferguson** [MortJC/homebridge-platform-orbit#22]
When creating automations in the Home app, the sprinkler will not show up as an available device to add to the automation.  It shows and works fine for manual control, but I can't create any automations with it.  Any ideas?  Thanks for your time and development on this, it's greatly appreciated.

**Comment by MortJC** [comment]
Hi,

Unfortunately the HomeKit does not support automation for sprinklers. This
applies to all sprinklers.

You have to use the native application to set up schedules.

Cheers James.
