### ISSUE TITLE
B-Hyve valve controls not appearing

### ISSUE THREAD

**Issue by jasonjcj** [MortJC/homebridge-platform-orbit#23]
After installing, unable to see B-Hyve valves in Home app.  I have three 8 valve controllers, for 24 individual valve objects.

**Comment by MortJC** [comment]
Hi, Can you please send me your debug log?

**Comment by jasonjcj** [comment]
@MortJC should i just upload my log file here?

**Comment by MortJC** [comment]
Just through this issue.

**Comment by jasonjcj** [comment]
actually, just updated the plugin and it's working beautifully!
