### ISSUE TITLE
Orbit Disconnects due to error after running for several days. 

### ISSUE THREAD

**Issue by ryanspire** [MortJC/homebridge-platform-orbit#24]
First of all, great work on this project! It works extremely well and allows me to set up automations that the Orbit app simply can't.

The problem I am experiencing is that the platform has a failure after running for several days and never recovers. Here is the situation:

- Running on a Raspberry Pi and configured correctly. All zones on my Orbit B-Hyve are represented in Homekit and can be controlled.
- After several days of flawless operation, the system stops responding.
- Homekit thinks that the signals have been properly sent to Orbit, but nothing happens with the irrigation system in the real world. 
- No errors reported in HomeKit itself (such as a 'Not Responding' indicator).
- Once in an error state the Orbit platform never recovers and stays inactive indefinitely. 
- The other 2 platforms configured in Homebridge continue to work properly once Orbit has stopped functioning.
- Restarting Homebridge fixes the problem for several more days (possibly as long as weeks).
- The Homebridge log indicates a Websocket error when no actions were in progress:

`Oct 01 07:41:33 raspberrypi homebridge[298]: [10/1/2020, 7:41:33 AM] [Orbit] WebSocket Error ErrorEvent {
Oct 01 07:41:33 raspberrypi homebridge[298]:   target: ReconnectingWebSocket {
Oct 01 07:41:33 raspberrypi homebridge[298]:     _listeners: { error: [Array], message: [Array], open: [Array], close: [] },
Oct 01 07:41:33 raspberrypi homebridge[298]:     _retryCount: 1,
Oct 01 07:41:33 raspberrypi homebridge[298]:     _shouldReconnect: true,
Oct 01 07:41:33 raspberrypi homebridge[298]:     _connectLock: false,
Oct 01 07:41:33 raspberrypi homebridge[298]:     _binaryType: 'blob',
Oct 01 07:41:33 raspberrypi homebridge[298]:     _closeCalled: false,
Oct 01 07:41:33 raspberrypi homebridge[298]:     _messageQueue: [ '{"event":"ping"}' ],
Oct 01 07:41:33 raspberrypi homebridge[298]:     onclose: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:     onerror: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:     onmessage: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:     onopen: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:     _handleOpen: [Function],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _handleMessage: [Function],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _handleError: [Function],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _handleClose: [Function],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _url: 'https://api.orbitbhyve.com/v1/events',
Oct 01 07:41:33 raspberrypi homebridge[298]:     _protocols: [],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _options: { WebSocket: [Function], connectionTimeout: 10000, maxRetries: 10 },
Oct 01 07:41:33 raspberrypi homebridge[298]:     send: [Function],
Oct 01 07:41:33 raspberrypi homebridge[298]:     _ws: WebSocket {
Oct 01 07:41:33 raspberrypi homebridge[298]:       _events: [Object: null prototype] {},
Oct 01 07:41:33 raspberrypi homebridge[298]:       _eventsCount: 0,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _maxListeners: undefined,
Oct 01 07:41:33 raspberrypi homebridge[298]:       readyState: 2,
Oct 01 07:41:33 raspberrypi homebridge[298]:       protocol: '',
Oct 01 07:41:33 raspberrypi homebridge[298]:       _binaryType: 'nodebuffer',
Oct 01 07:41:33 raspberrypi homebridge[298]:       _closeFrameReceived: false,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _closeFrameSent: false,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _closeMessage: '',
Oct 01 07:41:33 raspberrypi homebridge[298]:       _closeTimer: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _closeCode: 1006,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _extensions: {},
Oct 01 07:41:33 raspberrypi homebridge[298]:       _receiver: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _sender: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _socket: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _bufferedAmount: 0,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _isServer: false,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _redirects: 0,
Oct 01 07:41:33 raspberrypi homebridge[298]:       url: 'https://api.orbitbhyve.com/v1/events',
Oct 01 07:41:33 raspberrypi homebridge[298]:       _req: [ClientRequest]
Oct 01 07:41:33 raspberrypi homebridge[298]:     },
Oct 01 07:41:33 raspberrypi homebridge[298]:     _connectTimeout: Timeout {
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleTimeout: -1,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idlePrev: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleNext: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleStart: 403700923,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _onTimeout: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _timerArgs: undefined,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _repeat: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _destroyed: true,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(refed)]: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(asyncId)]: 624220,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(triggerId)]: 0
Oct 01 07:41:33 raspberrypi homebridge[298]:     },
Oct 01 07:41:33 raspberrypi homebridge[298]:     _uptimeTimeout: Timeout {
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleTimeout: -1,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idlePrev: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleNext: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _idleStart: 391168133,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _onTimeout: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _timerArgs: undefined,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _repeat: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       _destroyed: true,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(refed)]: null,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(asyncId)]: 604104,
Oct 01 07:41:33 raspberrypi homebridge[298]:       [Symbol(triggerId)]: 604093
Oct 01 07:41:33 raspberrypi homebridge[298]:     }
Oct 01 07:41:33 raspberrypi homebridge[298]:   },
Oct 01 07:41:33 raspberrypi homebridge[298]:   type: 'error',
Oct 01 07:41:33 raspberrypi homebridge[298]:   message: 'TIMEOUT',
Oct 01 07:41:33 raspberrypi homebridge[298]:   error: Error: TIMEOUT
Oct 01 07:41:33 raspberrypi homebridge[298]:       at ReconnectingWebSocket._handleTimeout (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
Oct 01 07:41:33 raspberrypi homebridge[298]:       at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
Oct 01 07:41:33 raspberrypi homebridge[298]:       at listOnTimeout (internal/timers.js:531:17)
Oct 01 07:41:33 raspberrypi homebridge[298]:       at processTimers (internal/timers.js:475:7)
Oct 01 07:41:33 raspberrypi homebridge[298]: }
`

It looks like the system will only retry for a maximum of 100 seconds, is it possible that losing an internet connection for less than 2 minutes will cause this problem?

**Comment by ryanspire** [comment]
Sorry for the formatting, here is a log file. 
[Homebridge-logs.txt](https://github.com/MortJC/homebridge-platform-orbit/files/5380429/Homebridge-logs.txt)

**Comment by MortJC** [comment]
Hi,

I've updated the websocket so it will keep retrying to connect forever.
That should sort out the issue.

Cheers.

**Comment by ryanspire** [comment]
Fantastic, thanks @MortJC! 

Unfortunately I won't be able to test it this year as I live in Canada and have already winterized my irrigation system. I am however quite sure that continuing to reconnect will solve the issue. I will monitor the logs and watch for the reconnection issue over the winter. 

Thank you very much for your work!

**Comment by ryanspire** [comment]
Hi @MortJC, I just realized I never followed up on the problem in the spring. The change to the retry duration certainly fixed the issue. Thanks again!
