### ISSUE TITLE
Battery Alerts

### ISSUE THREAD

**Issue by mattcostell** [MortJC/homebridge-platform-orbit#25]
[10/16/2020, 10:33:49 AM] [orbit] Unhandled message received: low_battery 

Above message is showing up in the logs - using the Orbit bluetooth hose controllers - would be great if those battery alerts could be surfaced through home.app?

Thanks!

**Comment by MortJC** [comment]
Hi,

Unfortunately the IrrigationSystem service has no battery characteristic, so I have no way of surfacing this to the home.app.

Cheers.
