### ISSUE TITLE
Zones limited to 10 minutes maximum

### ISSUE THREAD

**Issue by kellery82** [MortJC/homebridge-platform-orbit#26]
Is there any way to change the zones maximum time? I can only select 5 mins or 10 mins and because i have rotors, I want to select 50 minutes, but am unable to do so.

![image](https://user-images.githubusercontent.com/73224765/97141316-724cc100-1799-11eb-879e-286a5b0d9036.png)

My apologies if there is a reason for the 10 minute limit in the Home app.

Thanks in advance,

Kristopher

**Comment by MortJC** [comment]
Hi,

That's decided by the apple home app, and not something I can control.
However make sure you are running the latest versions of the IOS,
homebridge and the plugin.

Cheers.

**Comment by kellery82** [comment]
Thanks for the quick reply MortJC. Yep, I'm running the latest version of all three

**Comment by kellery82** [comment]
Seems to be an IOS14 issue as per the following;

[https://github.com/NRCHKB/node-red-contrib-homekit-bridged/issues/326](url)

**Comment by MortJC** [comment]
Thanks for the info.

Yep I'm having the same issue.
