### ISSUE TITLE
Always scheduled

### ISSUE THREAD

**Issue by vascott1** [MortJC/homebridge-platform-orbit#27]
Hi. Just installed your plugin after getting 2 b-hyve controllers. They show up in HomeKit just fine. The stats shows "scheduled" and when I ask Siri to start watering it always says "I've stopped watering your zone 1"

Manually it works fine.

Then when it is running I ask Siri to stop watering and the response is "ok, watering for 4 minutes"

Seems everything is backwards. Any suggestions. I have no schedules set at all. I checked.

Thanks!

**Comment by MortJC** [comment]
Hi,

Doesn't sound like it's related to the plugin, more an iOS / Home app
issue. Are you running the latest version of iOS, HomeBridge and the plugin?

Cheers

**Comment by vascott1** [comment]
Yes, yes and yes :) it might have resolved itself but still not sure. A bit more fiddling.   
  

  
Th ask for getting back to me :)
  
  
  
    
  

  
  
>

**Comment by Austinthemighty** [comment]
Just set mine up and the device icon in home shows scheduled even when I don't have any thing scheduled, and I cant set a schedule for it in the home app

**Comment by MortJC** [comment]
Hi,

Yes that's correct and a limitation of the home app.
