### ISSUE TITLE
Added to automation?

### ISSUE THREAD

**Issue by AtreyuArtax** [MortJC/homebridge-platform-orbit#31]
Just wondering if this can be added to an automation in Apple Home. It shows up and I can see the different zones to operate, but it is not available to add to automations i.e if Ring camera sees motion at 4am turn on irrigation zone 1.

**Comment by mitch7391** [comment]
I believe Apple is the reason behind this; they do not allow you to create those automations yet (hopefully in the future). It does not have anything to do with this plug-in.
