### ISSUE TITLE
Working with HomeKit, but Siri fails on set commands.

### ISSUE THREAD

**Issue by ryanspire** [MortJC/homebridge-platform-orbit#36]
This may not be a problem with homebridge-platform-orbit but after searching, I have not found any other irrigation systems that are experiencing the same problem so I am posting here. 

- In the fall they system was working perfectlhy, HomeKit, Siri, everything. 
- In the April I turned the system back on and updated to the latest version of homebridge-platform-orbit. I have the latest iOS software as well.
- I can use HomeKit to turn on and off any zones
- I can use the Orbit app to turn on a zone and the status is properly reflected in HomeKit
- If I ask Siri to turn on a zone Siri always comes back immediately with an error that says "Sorry, I didn't hear back from your devices....".  There is near zero wait time between the request and the error.
- There are no errors or any traffic at all in the Homebridge log file when this happens. 

Is anyone else experiencing this? I can not find any references to other irrigation controllers having this problem.

**Comment by MortJC** [comment]
Hi Ryan,

I had something similar a while ago. I ended up updating homebridge, all
npm modules and nodejs, and it's been reliable ever since. Hope that works
for you.

Cheers.

**Comment by MortJC** [comment]
That earning is fine. Does anything else in HomeKit work with Siri? Does it work through the home app?

**Comment by ryanspire** [comment]
I can turn on/off zones using HomeKit. If I turn a zone on/off in the Orbit app, it is reflected in Homekit. I have Homebridge plugins for Smartthings (with several devices) and Somfy (for shades and blinds) and Siri works for them. Siri for Orbit is the only thing that is not working. It certainly has me stumped.

**Comment by ryanspire** [comment]
I have also verified that there is nothing anomalous when running in debug mode and when using Siri to attempt to start a zone absolutely nothing happens in Homebridge. It seems like an apple thing but I don't know why other irrigation system users are not having the same problem.

**Comment by MortJC** [comment]
I've checked mine and it's also not working now. So something has changed
wither in HomeBridge or on the Apple Home side. However phrases like "Hey
Srini, What's the status of the Front Garden Zone" returns "Front Garden is
not being watered".

I've also put HAP-NodeJS module in debug mode using "set
DEBUG=HAP-NodeJS:*" and it's showing Siri is not trying to talk to
HomeBridge for the commands that are failing. Leads me to believe the
initial configuration/registration of this device is where the trouble
lies. I'm trying to identify the issue. Will update when I work this out...

**Comment by ryanspire** [comment]
Thanks for looking into it @MortJC !

**Comment by MortJC** [comment]
Converted the code to TypeScript, when through the specification thoroughly, added all Characteristics, still can't turn on the valves from Siri. Works from Apple home app and check the status of the valves from Siri. Not sure where to go from here and I assume it's an issue with Siri as it doesn't query the homebridge for the activate commands.

**Comment by MortJC** [comment]
Looks like it's an Apple HomeKit issue. Users of Rachio are also reporting the same issue. https://community.rachio.com/t/the-official-homekit-updates-thread/29583.

**Comment by Hucksleyy91** [comment]
Hey guys if you use the eve app you can create a scene for the valve to be on and then say turn on (scene name) :) works a treat for me

**Comment by MortJC** [comment]
Is this still an issue for you?

**Comment by ryanspire** [comment]
This is still an issue for me. Unfortunately I won’t be able to help test if a fix is in the works as I will be shutting my system down on Saturday for the winter.

**Comment by MortJC** [comment]
This issue appears to have been resolved in a recent release.
