### ISSUE TITLE
WebSocket Error ErrorEvent

### ISSUE THREAD

**Issue by EvoSems** [MortJC/homebridge-platform-orbit#38]
Hi Mate. not sure what's causing the error. was working fine for a long time. any pointers? many thanks

[B-Hyve 4 Irrigation] WebSocket Error ErrorEvent {
  target: ReconnectingWebSocket {
    _listeners: { error: [], message: [], open: [], close: [] },
    _retryCount: 0,
    _shouldReconnect: true,
    _connectLock: false,
    _binaryType: 'blob',
    _closeCalled: false,
    _messageQueue: [],
    onclose: [Function (anonymous)],
    onerror: [Function (anonymous)],
    onmessage: [Function (anonymous)],
    onopen: [Function (anonymous)],
    _handleOpen: [Function (anonymous)],
    _handleMessage: [Function (anonymous)],
    _handleError: [Function (anonymous)],
    _handleClose: [Function (anonymous)],
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _protocols: [],
    _options: {
      WebSocket: [Function],
      connectionTimeout: 10000,
      maxReconnectionDelay: 64000,
      minReconnectionDelay: 2000,
      reconnectionDelayGrowFactor: 2
    },
    send: [Function (anonymous)],
    _ws: WebSocket {
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _closeCode: 1006,
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _extensions: {},
      _protocol: '',
      _readyState: 2,
      _receiver: null,
      _sender: null,
      _socket: null,
      _bufferedAmount: 0,
      _isServer: false,
      _redirects: 0,
      _url: 'wss://api.orbitbhyve.com/v1/events',
      _req: [ClientRequest],
      [Symbol(kCapture)]: false
    },
    _connectTimeout: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 44800,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 705,
      [Symbol(triggerId)]: 0
    }
  },
  type: 'error',
  message: 'TIMEOUT',
  error: Error: TIMEOUT
      at ReconnectingWebSocket._handleTimeout (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:529:42)
      at Timeout.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:524:75)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

**Comment by MortJC** [comment]
Hi.

The error is basically saying you can't connect to wss://
api.orbitbhyve.com/v1/events. Can you ping api.orbitbhyve.com?

**Comment by sayhicoelho** [comment]
How to try to reconnect after timeout? My server was down for a few minutes and then it came back again, but my websocket client just crashed after timeout.

**Comment by MortJC** [comment]
It should auto reconnect.

Please provide a debug log.
