### ISSUE TITLE
Orbit b-hyve smart hose controller shown as “Scheduled”

### ISSUE THREAD

**Issue by dfizzo** [MortJC/homebridge-platform-orbit#40]
Orbit b-hyve smart hose controller shown as “Scheduled” in Home app. Rather than "Off". I have had this issue for some time.

**Comment by MortJC** [comment]
Have you programmed it in the Orbit app?

**Comment by dfizzo** [comment]
All set now. As suspected, I had programmed schedules — that were not enabled in B-Hyve app. I deleted the programs scheduled and now functioning properly on Home App. Interestingly, this issue only occurred in Home App. In Home+, was showing as “Off” even with the programs scheduled. Thanks for the help, @MortJC!

_________________________________________
Daniel M. Fein
Tel: 609-203-2665
Email: ***@***.***
_________________________________________

On Sep 23, 2021, at 10:41 PM, MortJC ***@***.***> wrote:

﻿
Have you programmed it in the Orbit app?
