### ISSUE TITLE
Using Siri doesn't make the tile active

### ISSUE THREAD

**Issue by homersdonut** [MortJC/homebridge-platform-orbit#49]
When I use Siri to turn one of my sprinklers on, it works great and turns it on and off. However when it’s on, the tile still appears inactive, so unless you visually saw it running, you wouldn't know it was on from looking at the HomeKit tile. Interestingly as well, when you use Siri to turn on a sprinkler, it also doesn't ”run” or appear active in the B-Hyve app. Which isn’t a big deal, but would be nice to be able to tell if it was on in HomeKit.

**Comment by MortJC** [comment]
Hi. My system shows it's running when you ask Siri to turn it on, both in
the tile view and with the Bhyve device open. Which device do you have and
can you send me the debug logs?

**Comment by homersdonut** [comment]
Hey - Thanks for the reply. I actually ended up overhauling my entire homebridge setup and reinstalled everything. I also ended up getting a bhyve XD. When I use siri to turn each zone on from that, the tile does appear active each time. For the one 21005 I kept, it still doesn't make the tile active when I use siri. The log files doesn't indicate anything other than it being set to ACTIVE when I turn it on, and INACTIVE when I turn it off (with siri).

edit: Is there a way to tuen notifications on for HomeKit? that might be a workaround way to know it’s active even if the tile isn't.

**Comment by homersdonut** [comment]
captured this  morning:

[orbit] WebSocket Error ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /v1/events HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: DHvdrEaPxOHIrKgnbXurDg==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: api.orbitbhyve.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/events',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.orbitbhyve.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 500',
  error: Error: Unexpected server response: 500
      at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/ws/lib/websocket.js:767:7)
      at ClientRequest.emit (node:events:527:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at TLSSocket.socketOnData (node:_http_client:494:22)
      at TLSSocket.emit (node:events:527:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
}
[5/21/2022, 8:31:05 AM] [orbit] WebSocket Error ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1006,
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _extensions: {},
    _protocol: '',
    _readyState: 2,
    _receiver: null,
    _sender: null,
    _socket: null,
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://api.orbitbhyve.com/v1/events',
    _req: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [TLSSocket],
      _header: 'GET /v1/events HTTP/1.1\r\n' +
        'Sec-WebSocket-Version: 13\r\n' +
        'Sec-WebSocket-Key: iH157RcfkSLB8EGQjAtizg==\r\n' +
        'Connection: Upgrade\r\n' +
        'Upgrade: websocket\r\n' +
        'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\n' +
        'Host: api.orbitbhyve.com\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: undefined,
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/v1/events',
      _ended: false,
      res: [IncomingMessage],
      aborted: true,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: [HTTPParser],
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.orbitbhyve.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(kError)]: undefined
    },
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'Unexpected server response: 500',
  error: Error: Unexpected server response: 500
      at ClientRequest.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-orbit/node_modules/ws/lib/websocket.js:767:7)
      at ClientRequest.emit (node:events:527:28)
      at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:631:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at TLSSocket.socketOnData (node:_http_client:494:22)
      at TLSSocket.emit (node:events:527:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
}

**Comment by MortJC** [comment]
Hi. Does that error get thrown all the time?

**Comment by homersdonut** [comment]
> Hi. Does that error get thrown all the time?
> […](#)

It does, I just checked the logs. To be honest I had to stop using it through homekit because it just doesn’t work reliably. It seems to work for mine for a day or two through homekit and then it just doesn’t respond until it’s rebooted again. I have random success with Siri as well. I’ve had to just go back to the b-hyve app unfortunately.

**Comment by MortJC** [comment]
I see it occasionally also, like once a week. I'm guessing maybe the vendor periodically restarts their system.
