### ISSUE TITLE
One hose timer missing Zone configuration.

### ISSUE THREAD

**Issue by anshukapoor** [MortJC/homebridge-platform-orbit#50]
I have 4 orbit hose timers. 3 of them show up well in the Home app very well, but one is missing the Zone configuration. Because of this there is no on/off switch and I cannot set the default runtime of that hose timer. 

Hose timer with zone configuration:
![image](https://user-images.githubusercontent.com/43589240/181581614-f86ac5e8-255a-4bc9-bfb6-58800521d1a9.jpeg)

Hose timer with missing zone configuration:
![image](https://user-images.githubusercontent.com/43589240/181581658-26010ccd-1a7d-4ed1-87e6-ddf0cf61c52e.jpeg)

Appreciate anybodys help with this.

**Comment by MortJC** [comment]
Hi, are they all the same model?

Can you please enable debug, restart homebridge and send the log.

**Comment by anshukapoor** [comment]
Hello James

I am new to home bridge, so please forgive me if I did this wrong.
I enabled the debug mode by setting the 'Homebridge Debug Mode -D' flag from the UI, screen shot below

![homebridge debug](https://user-images.githubusercontent.com/43589240/181754046-6e03133b-1147-4fc9-920e-53da83e70be7.jpg)

Here are the orbit plugin related logs.
[homebridge.log.txt](https://github.com/MortJC/homebridge-platform-orbit/files/9219692/homebridge.log.txt)


Appreciate your help with this.

**Comment by anshukapoor** [comment]
Hello James

I uninstalled and the installed the plugin and it resolved the issue of missing zone on the faucet timer.
