### ISSUE TITLE
B-Hyve Battery and Charge Status

### ISSUE THREAD

**Issue by mitch7391** [MortJC/homebridge-platform-orbit#6]
@MortJC just want to thank you first for getting this working, I was one of the first testers from Cody’s plug-in and have been dying for him to finish it or get it working. Thanks to you I got my B-Hyve 6 zone WiFi controller to work from HomeKit for the first time :)

I was wondering if you can get other statuses in it? I noticed the Cody’s version had a battery level and charging status (even though the unit is plugged into mains power), it would be nice to have the charging status. Also I wonder if the battery is the internal memory battery? So maybe that is still important.

**Comment by MortJC** [comment]
Hi Mitch7391,

Thanks for the feedback.

In regards to the battery level, I don't think that applies to the mains
versions as I'm not getting any data from the API in regards to battery
level. I'm guessing if I had a battery powered device I might get the data.

Cheers James.

**Comment by mitch7391** [comment]
That is fair, maybe it was a bug in the previous plug-in? It always confused me and that’s why I thought it might have been an internal memory battery or something.

**Comment by mitch7391** [comment]
Funny enough @MortJC when I rebooted homebridge this morning after an update, I received the following error which I could swear I had seen once before since installing your plug-in:

[4/15/2020, 6:25:57 AM] [BHyve] Unhandled message received: clear_low_battery

The B-Hyve happened to be running its scheduled run at the time.

**Comment by MortJC** [comment]
Can't really do much with that unless there's another status.

I think the battery status is really for the battery powered devices.

**Comment by mitch7391** [comment]
I will see if I can get that status at all in debug mode if that would help? That appeared in my normal Homebridge logs whilst it was running.

**Comment by wallacepost** [comment]
27/05/2020, 5:10:30 am [orbit] Unhandled message received: clear_low_battery

**Comment by MortJC** [comment]
Hi, what issue are you reporting?

**Comment by mitch7391** [comment]
I am assuming they are getting the same message as me in their Homebridge logs? Just as an FYI I still receiver this message with each reboot of Homebridge.

**Comment by MortJC** [comment]
Thanks for the info.

**Comment by genesispc** [comment]
Just to let you know I have also received the "[orbit] Unhandled message received: clear_low_battery" this morning. Will keep an eye out for it happening again.
I'm new to the whole homebridge scene. Is there a way to dump the messages being sent just by the orbit?

**Comment by MortJC** [comment]
Hi

Yes that event can be ignored.

If you run it in Debug you can see all the messages.

Cheers.

**Comment by mitch7391** [comment]
@MortJC I’m not sure if I’m missing something here, but is there anyway we can stop the alarm coming up in our logs? Or if it is a real alarm is there anyway to use it like how other accessories can display a low battery status? It’s just that I still have it coming up in my logs with no resolution to what is to happen to it. If I can I reduce one more alarm in my logs that is a plus.

**Comment by MortJC** [comment]
Hi, it's not an alarm, just an unhandled message that we are not interested
in as there is no way to do anything with this event.

**Comment by mitch7391** [comment]
Sorry alarm was a poor choice of words. So it is just definitely something we have to ignore? It can’t be removed in any way?

**Comment by MortJC** [comment]
Yes it can be ignored.
