### ISSUE TITLE
B-Hyve Rain Sensor Indication 

### ISSUE THREAD

**Issue by mitch7391** [MortJC/homebridge-platform-orbit#7]
I am not sure if you have been on the B-have forums but there has been a massive request from the public to have the app display when the rain sensor has been triggered. Orbit have been very reluctant to do so and their app currently only shows the rain sensor active once a zone has been started. There must be a way to grab this info from the unit or the API.

If you could find this data, I was wondering if this could be used to create an occupancy sensor to act as a rain sensor? That would be a really awesome feature if it is possible :)

**Comment by MortJC** [comment]
Hi Mitch7391,

I've had a look for the rain sensor in the API data and can't see it. Could
be my rain sensor isn't working as it's from a different manufacturer.

Can you try running your homebridge with -D? This will display the API
messages. Try wetting your rain sensor and check if you can see any
messages that looks like they are related.

Cheers James.

**Comment by mitch7391** [comment]
@MortJC maybe it is related to the issues I have seen in the forums where Orbit keep saying the app will only show it if it’s active when a program is running. This was the response I got from one of their devs:

“You will only see the rain sensor is active if the timer is trying to run a program when the sensor is active.”

I am hoping it’s just an issue of they can’t be bothered doing it vs it can’t be done. It must know the sensor is already active. I really hope they change this to show the sensor active when it first activated, not only once the program runs and it is active. This would be a cool way to integrate a rain sensor into my home automation. Hopefully we can find it through your plug-in haha.

I will try what you have suggested in a day or two when I have finished nightshifts and let you know what I discover :)

**Comment by mitch7391** [comment]
@MortJC is there a way to turn debug on for just this plug-in only? When I turn debug on for homebridge it just spams my with everything (I have about 40 accessories on homebridge). I am using config-ui-x and it is hard to grab the logs as they are scrolling. Also the debug seems to be inconsistent in what it gives me. Twice it gave massive data dumps of a gaint array and I know I saw the word 'rainsensor' or 'rain_sensor' in there but missed grabbing those logs and havent been able to reproduce it. Is there any guidance you night be able to give me to get this data for you?

**Comment by mitch7391** [comment]
Actually I kept trying and I finally did get the status again through debug mode:

[4/16/2020, 4:11:41 PM] [BHyve] RX {"event":"watering_in_progress_notification","program":"a","current_station":4,"run_time":1,"started_watering_station_at":"2020-04-16T08:11:46.000Z","rain_sensor_hold":true,"device_id":"5dac38b24f0c47ece9f25cd4","timestamp":"2020-04-16T08:11:46.000Z"}

[4/16/2020, 4:11:41 PM] [BHyve] Watering_in_progress_notification Station 4 Runtime 1

**Comment by MortJC** [comment]
Interesting, did the program still run?

No, debug will be turned on for all plugins.

On linux you could pipe the output through grep "BHyve" or on windows pipe
it through find "BHyve".

**Comment by mitch7391** [comment]
So I set up a temporary auto sequence to run and held the clicker down on the rain sensor to activate it, once it actives it stops the sequence running, then I release the button and the sequence kicks back in if it still has time remaining. This does not override manual runs though. Does this status help you find it in the code at all?

I can do that if you need me to try look for a further be dug status?

**Comment by MortJC** [comment]
Hi,

I don't think it worth pursuing this unless the IrrigationSystem has a
Characteristic exposed that is suitable and the Bhyve exposes the status in
a consistently readable manner.

Cheers.

**Comment by mitch7391** [comment]
Hey James thanks for being upfront, I guess as a starting point I will try work on Orbit to include the status in the API properly as a starting point. Thanks anyway :)
