### ISSUE TITLE
Zone ‘Stopping’ Status

### ISSUE THREAD

**Issue by mitch7391** [MortJC/homebridge-platform-orbit#8]
Hey @MortJC I noticed an issue today my scheduled watering was taking place. Even though the B-Hyve was currently running it was showing as ‘stopping’ in HomeKit.

![A84DC104-352E-47FC-9704-A44C1A0C230C](https://user-images.githubusercontent.com/40288237/79331412-aa9f5700-7f4d-11ea-987f-17891f629134.png)
![98FD1F85-2F24-48EF-B80A-2F4A010FAE94](https://user-images.githubusercontent.com/40288237/79331419-af640b00-7f4d-11ea-89af-d940644251e2.png)

And later this evening I have looked in HomeKit and seen that it thinks my B-Hyve is still running when it is not. I drilled down into the group accessory to see it thinks it is ‘stopping‘ still and is therefore still on.

![7E9DE7A8-F96C-4644-8258-91259FF1730C](https://user-images.githubusercontent.com/40288237/79331566-ee925c00-7f4d-11ea-99b7-bc2eb8ae8866.png)
![A5A83F4D-5622-4596-B95A-71B0EE721240](https://user-images.githubusercontent.com/40288237/79331572-f18d4c80-7f4d-11ea-917d-e86c4e629962.png)

I tired to run the station station for a few minutes to see if it would clear it and it did not, it just stays on that status. Any thoughts on this one?

**Comment by mitch7391** [comment]
@MortJC I have since broken the accessory apart as it’s separate tiles for further testing and noticed that if I manually start a zone separate of the ‘controller’ accessory; it starts the sprinkler zone but in HomeKit it just shows as idle. It stays like this after the zone is finished until I manually switch the zone off in HomeKit. 

![7BFB1D49-CE65-4E6C-97C9-34C354892193](https://user-images.githubusercontent.com/40288237/79536362-78f3d080-80b2-11ea-8581-d3b4c389572f.png)
![E901591B-D812-496F-B879-A13C501C895A](https://user-images.githubusercontent.com/40288237/79536367-7c875780-80b2-11ea-93ba-5befe50ee00e.jpeg)

Sorry for spamming with all of these potential bugs, I am just excited this is going and want to help identify any issues 😊

**Comment by MortJC** [comment]
Hi,

I think all these issues are related to websocket connection to the bhyve
API having closed. I've updated the code to auto reconnect.

Update to the latest from npm.

Cheers.

**Comment by mitch7391** [comment]
Thanks for the update James, I have posted a problem with the update in issue #9 seen as they are most likely related :)

**Comment by mitch7391** [comment]
Resolved in issue #9.
